version: '3'

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: transaction
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
